//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientDevice()
        {
            this.upgradesReplacements = new HashSet<upgradeReplacement>();
            this.requestedServices = new HashSet<requestedService>();
        }
    
        public int Id { get; set; }
        public string modelName { get; set; }
        public string serialNumber { get; set; }
        public string description { get; set; }
        public int typeOfDeviceId { get; set; }
        public int contractId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upgradeReplacement> upgradesReplacements { get; set; }
        public virtual typeOfDevice typeOfDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requestedService> requestedServices { get; set; }
        public virtual contract contract { get; set; }
    }
}
