//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contract()
        {
            this.clientDevices = new HashSet<clientDevice>();
        }
    
        public int Id { get; set; }
        public System.DateTime dateOfReceipt { get; set; }
        public System.DateTime approximateEndDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public int approximateCost { get; set; }
        public Nullable<int> endCost { get; set; }
        public int clientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientDevice> clientDevices { get; set; }
        public virtual client client { get; set; }
    }
}
