//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public module()
        {
            this.numberInStock = 0;
            this.needToOrder = 0;
            this.safetyStock = 0;
            this.moduleCharacteristics = new HashSet<moduleCharacteristic>();
            this.upgradeReplacements = new HashSet<upgradeReplacement>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public short numberInStock { get; set; }
        public short needToOrder { get; set; }
        public short safetyStock { get; set; }
        public int typeOfModuleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moduleCharacteristic> moduleCharacteristics { get; set; }
        public virtual typeOfModule typeOfModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upgradeReplacement> upgradeReplacements { get; set; }
    }
}
