//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviceExecution
    {
        public int Id { get; set; }
        public int employeeId { get; set; }
        public int requestedServiceId { get; set; }
        public System.DateTime dateOfBegin { get; set; }
        public Nullable<System.DateTime> dateOfEnd { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual requestedService requestedService { get; set; }
    }
}
