//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class serviceCenterEntities : DbContext
    {
        public serviceCenterEntities()
            : base("name=serviceCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<characteristic> characteristics { get; set; }
        public virtual DbSet<clientDevice> clientsDevices { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<contract> contracts { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<requestedService> requestedServices { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<typeOfDevice> typesOfDevices { get; set; }
        public virtual DbSet<typeOfModule> typesOfModule { get; set; }
        public virtual DbSet<unit> units { get; set; }
        public virtual DbSet<upgradeReplacement> upgradesReplacements { get; set; }
        public virtual DbSet<moduleCharacteristic> moduleCharacteristics { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<stageOfImplementation> stagesOfImplementations { get; set; }
        public virtual DbSet<serviceExecution> servicesExecution { get; set; }
    }
}
