//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIew_contractsExecution
    {
        public int Id { get; set; }
        public string clientFio { get; set; }
        public string ClientPhone { get; set; }
        public System.DateTime dateOfReceipt { get; set; }
        public System.DateTime approximateEndDate { get; set; }
        public int approximateCost { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string executionProcess { get; set; }
    }
}
