//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_requestedServices
    {
        public int Id { get; set; }
        public string typeNeme { get; set; }
        public string deviceName { get; set; }
        public string deviceDescription { get; set; }
        public string serviceName { get; set; }
        public string serviceDescription { get; set; }
        public System.DateTime approximateEndDate { get; set; }
        public string stages { get; set; }
    }
}
